using UnityEngine;
using NaughtyAttributes;
using System.Collections;
using System.Linq;
using System.Collections.Generic;
using System;
using System.IO;
#if UNITY_EDITOR
using UnityEditor;
using Unity.EditorCoroutines.Editor;
#endif

[CreateAssetMenu(fileName = "TileSet", menuName = "TileSet", order = 0)]
public class TileSet : ScriptableObject
{
    public List<Tile> tiles;

#if UNITY_EDITOR
    [InfoBox("Prefabs (autogenerated or not) should be in /Mesh\nSOs will be created in /Tiles\nPrefabs starting with _ will be ignored")]
    public string path = "Assets/Tiles";

    static readonly Ray[] rays = GenerateRays();

    static Ray[] GenerateRays()
    {
        var dir = new Vector3(0, -1, 0);
        float mul = 0.9f;
        float h = Mathf.Sqrt(3) / 2;
        h *= mul;

        return new Ray[12]
        {
            // terrains 
            new(new(mul/2 , 10, h ),dir),
            new(new(mul   , 10, 0 ),dir),
            new(new(mul/2 , 10, -h),dir),
            new(new(-mul/2, 10, -h),dir),
            new(new(-mul  , 10, 0 ),dir),
            new(new(-mul/2, 10, h ),dir),

            // utilities
            new(new(0     , 10, h   ),dir),
            new(new(0.75f , 10, h/2 ),dir),
            new(new(0.75f , 10, -h/2),dir),
            new(new(0     , 10, -h  ),dir),
            new(new(-0.75f, 10, -h/2),dir),
            new(new(-0.75f, 10, h/2 ),dir),
        };
    }

    /*[Button]
    void ProcessSelected()
    {
        var gos = Selection.GetFiltered<GameObject>(SelectionMode.Unfiltered);

        ProcessPrefabs(gos.ToList());

        Debug.Log($"Processed {gos.Length} prefabs");
    }*/

    //[Button]
    void ProcessAll()
    {   
        List<string> paths = new();
        RecursiveSearch(new DirectoryInfo(path + "/Meshes"));

        // filters out prefabs starting with _ and main assets
        var prefabs = paths.Select(path => AssetDatabase.LoadAllAssetsAtPath(path))
                .SelectMany(x => x)
                .Select(x => x as GameObject)
                .Where(x => x != null && !x.name.StartsWith('_') && AssetDatabase.IsSubAsset(x.GetInstanceID()))
                .ToList();

        int progId = Progress.Start("Processing prefabs...");
        EditorCoroutineUtility.StartCoroutine(Coroutine(), this);

        void RecursiveSearch(DirectoryInfo dir)
        {
            foreach (var fi in dir.GetFiles())
            {
                if (fi.Extension != ".meta")
                    paths.Add(fi.FullName[fi.FullName.LastIndexOf("Assets")..]);
            }

            foreach (var di in dir.GetDirectories())
                RecursiveSearch(di);
        }

        IEnumerator Coroutine()
        {
            for (int i = 0; i < prefabs.Count; i++)
            {
                ProcessPrefab(prefabs[i]);

                Progress.Report(progId, i, prefabs.Count);
                yield return null;
            }

            Progress.Remove(progId);
            Clean();
        }
    }

    void ProcessPrefab(GameObject prefab)
    {
        Tile so = tiles.Find(x => x.prefab);
        if (so == null)
        {
            so = CreateInstance<Tile>();
            so.name = prefab.name;
            so.prefab = prefab;
            AssetDatabase.CreateAsset(so, path + "/Tiles/" + prefab.name + ".asset");
        }
        
        var colors = ColorPicker.ColorpickMultiple(prefab,rays);
        foreach (var c in colors)
            Debug.Assert(c.hit==false);

        //so.terrains = colors [0..5 ].Select(c => c.color.ToTerrainType()).ToArray();
        //so.utilities = colors[6..11].Select(c => c.color.ToUtilityType()).ToArray();
    }

    void Clean()
    {
        var deleted = tiles.Where(x => x.prefab == null).ToList();
        tiles = tiles.Except(deleted).ToList();

        List<string> failedPaths = new();
        AssetDatabase.DeleteAssets(deleted.Select(x => AssetDatabase.GetAssetPath(x)).ToArray(), failedPaths);
        if (failedPaths.Count > 0)
            Debug.LogWarning($"Failed to delete {failedPaths.Count} assets");
    }

    [DrawGizmo(GizmoType.Active)]
    static void DrawGizmo(Transform scr, GizmoType gizmoType)
    {
        Gizmos.color = Color.cyan;
        int i = 0;
        foreach (var ray in rays)
        {
            if (i == 6)
                Gizmos.color = Color.white;

            Gizmos.DrawSphere(ray.origin, 0.05f);
            Gizmos.DrawRay(ray);

            i++;
        }
    }

    //[Button]
    void Test()
    {
        var dic = Selection.objects.Select(x => x.GetType())
            .Aggregate(new Dictionary<Type, int>(), (acc, t) =>
            {
                if (!acc.TryAdd(t, 1))
                    acc[t]++;
                return acc;
            });

        foreach (var kvp in dic)
        {
            Debug.Log($"{kvp.Key.ToString()}     {kvp.Value}");
        }
    }

    //[Button]
    void Test2()
    {
        List<string> paths = new();
        RecursiveSearch(new DirectoryInfo(path));

        foreach (var p in paths)
            foreach (var obj in AssetDatabase.LoadAllAssetsAtPath(p))
            {
                Debug.Log(obj);
            }

        void RecursiveSearch(DirectoryInfo dir)
        {
            foreach (var fi in dir.GetFiles())
            {
                if (fi.Extension != "meta")
                    paths.Add(fi.FullName[fi.FullName.LastIndexOf("Assets")..]);
            }

            foreach (var di in dir.GetDirectories())
                RecursiveSearch(di);
        }
    }

    //[Button]
    void Test3()
    {
        var assets = AssetDatabase.LoadAllAssetsAtPath("Assets/Tiles/Meshes/Hexagonal WFC.fbx")
            .Select(x => x as GameObject)
            .Where(x => x != null && !x.name.StartsWith('_') && AssetDatabase.IsSubAsset(x.GetInstanceID()))
            .ToList();
        foreach (var go in assets)
        {
            Debug.Log($"{go.name}      {go.GetComponent<MeshFilter>().sharedMesh}      {go.GetComponent<MeshRenderer>().sharedMaterials.Length}");
        }
    }
#endif
}
